# Generated by Django 3.0.6 on 2020-05-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
